### ISSUE TITLE
Implement StickBreakingTransform.log_abs_det_jacobian()

### ISSUE THREAD

**Issue by fritzo** [probtorch/pytorch#112]
This is needed to do HMC over simplex-constrained random variables, e.g. for `Dirichlet` random variables.

It would really help to have tests #110 complete to test correctness of this tricky bit of math.

**Comment by fritzo** [comment]
This is being implemented in https://github.com/pytorch/pytorch/pull/5547

**Comment by fritzo** [comment]
This was implemented in pytorch#5547 but is buggy and does not work. We should add tests and fix the bugs.

@alshedivat Have you used `StickBreakingTransform.log_abs_det_jacobian()` at all? Do you have any ideas for tests?

**Comment by alshedivat** [comment]
@fritzo, my implementation is based on [Stan's reference manual, v2.17.0](https://github.com/stan-dev/stan/releases/) (Section 35.6, pp. 408-410) and uses the inverted stick-breaking construction. I also used an offset as suggested in the manual to make sure all zeros vector maps to the center of the simplex. I have used `LogisticNormal` distribution which is based on this transform.

**Note:** The original implementation of the `StickBreakingTransform` (before  pytorch#5547) was slightly different. Could the bugs be due to assuming a particular form of the transform? (E.g., assuming no offset?). Could you elaborate more on what the bug is?

Edward uses [the same construction](https://github.com/blei-lab/edward/blob/master/edward/util/tensorflow.py#L104-L150) in their `to_simplex` util function. We can borrow [some tests](https://github.com/blei-lab/edward/blob/master/tests/util/to_simplex_test.py) from there, but I'm not sure if they have `log_abs_det_jacobian` implemented and tested.

@dustinvtran, do you happen to know a good way to test `StickBreakingTransform`? How is it done in Edward or Stan? (I can't find the relevant code.)

**Comment by fritzo** [comment]
@alshedivat Thanks for explaining. @SsnL pointed out that we could use [torch.slogdet](http://pytorch.org/docs/master/torch.html#torch.slogdet), but we would need to deal with the Jacobian not being square.

**Comment by dustinvtran** [comment]
Thanks for pinging me. We haven't implemented and tested a `log_abs_det_jacobian` for the stick breaking transform. I wholeheartedly agree with this direction though :) Stick breaking transforms are great.
