### ISSUE TITLE
Implement TransformDistribution with multiple base distributions?

### ISSUE THREAD

**Issue by vishwakftw** [probtorch/pytorch#129]
I find this very useful, when implementing certain distributions. I think this would be a bit non-trivial, but is it actually possible to do this?

**Comment by fritzo** [comment]
Well it might make mathematical sense to implement a `StackDistribution` in analogy to `torch.stack`. This is nice theoretically because it is a categorical product. But in practice, I don't see it simplifying code or increasing correctness, so I'd opt to simply write those cases out by hand. Also in many cases you'd want to transform multiple distributions of different tensor shape, and by the time you add all the `.contiguous().view()` reshaping logic to make this work for a transformed distribution, I suspect the code harder to maintain than simply writing out the transformation manually.

**Comment by vishwakftw** [comment]
Thanks @fritzo . Considering the difficulty in this task, I will close it.
