### ISSUE TITLE
Implement OneHotCategorical

### ISSUE THREAD

**Issue by fritzo** [probtorch/pytorch#5]

**Comment by jwvdm** [comment]
TensorFlow defines [tf.contrib.distributions.OneHotCategorical](https://www.tensorflow.org/api_docs/python/tf/contrib/distributions/OneHotCategorical) for this purpose, which is a distinct class from [tf.contrib.distributions.Categorical](https://www.tensorflow.org/api_docs/python/tf/contrib/distributions/Categorical). I think this is probably a good idea, since samples from the two distributions have different types (one-hot vector, vs integer).
